### PR TITLE
Install Mobilizon with pre-built package

### LINKED ISSUE #75: Use prebuilt Mobilizon release
### Describe the bug

Installing Mobilizon requires a bunch of dependencies (system softwares, Node.js, Elixir) just to _build_ the app. It does not go well on 2GB VMs having a NextCloud running for example.

The installer exits when webpack tries to produce a "modern" build.

### Solution

[Use the prebuilt release](https://framagit.org/framasoft/mobilizon/-/merge_requests/774) ~~once it is ready~~ as it is ready. 

In term of impact:

- imagemagick and other image libs won't be needed
- node.js won't be needed
- elixir won't be needed — a standalone runtime will be bundled
- configuration will change, and rely solely on environment variables ([the ones listed in `releases.exs`](https://framagit.org/framasoft/mobilizon/-/blob/master/docker/production/releases.exs))

Maybe other things I missed?

### PR DESCRIPTION
**Pull request by oncletom**
## Problem

Mobilizon requires a lot of dependencies, time and resources to be built before working.

fixes #75

## Solution

This PR fetches a pre-built version of Mobilizon, and makes it running.

- [x] I have not been able to connect with a LDAP user, and raised [issue #555](https://framagit.org/framasoft/mobilizon/-/issues/555) on Mobilizon issue tracker;
- [x] I have opened [merge request 796](https://framagit.org/framasoft/mobilizon/-/merge_requests/796) to be able to configure HTTP port without a hack.

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [x] Can be reviewed and tested.

### CODE REVIEW

**Comment by oncletom** [comment]
I have successfully installed `mobilizon@1.0.3` with the current `install` script.

I am not entirely sure about the `upgrade` script though, as many dependencies have been removed (Elixir, Node, system deps).

For some reason, the GitLab release asset of my fork asks for a password so I sticked to the bare package registry artifacts.

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
Sorry, but when I read your solution, I thought the pre-built version was a native built, not a vagrant container.

In addition, the source file are on your personal git repository and we prefer to stick to official git.

**Comment by oncletom** [comment]
Hm, I'm not sure to understand:

- I used Vagrant to automate the local install, it's not mandatory nor part of the process (it just helps me)
- The official build will be produced by the next Mobilizon release, so it will be a matter of changing the URL (my initial PR statement)

So, what don't you understand? I'm happy to clarify.

**Comment by oncletom** [comment]
Mobilizon is now producing releases based on the work I shared in this pull request:

- artifacts are published on the official repo: https://framagit.org/framasoft/mobilizon/-/releases
- they seem to be changing a few things in the process as part of https://framagit.org/framasoft/mobilizon/-/merge_requests/815

In the meantime, I'm disappointed by being ignored, shut down and put away.
I won't be committing any additional time or effort, unless you find it wise to apologize, and that you demonstrate you have understood what you apologize for.

**Pull request closed without merging**
