### PR TITLE
Testing

### LINKED ISSUE #140: E-Mail verification from users without an account doesn't work
Hi there,

I am on the latest version. I have created an event and sent the link to people without a mobilizon account. They want to take part, but they don't get the verification mail.

Do I need to setup mail manually?

Regards,

Stefan

### PR DESCRIPTION
**Pull request by yalh76**
## Problem

- *Fix #140*

## Solution

- *Update configuration regarding https://framagit.org/framasoft/mobilizon/-/blob/main/UPGRADE.md#upgrading-from-20-to-21*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by rodinux** [comment]
Sorry, I have a doubt... I just realize the users on my instance can't register... The bug is similar at this one: https://framagit.org/framasoft/mobilizon/-/issues/1204
And it makes long time it is broken, perhaps since this release...

**Comment by rodinux** [comment]
I confirm, since this fix in 14 the users can't register, the registration on my instance was the vendredi 16 septembre 2022 à 11:28

**Comment by rodinux** [comment]
I have try on my fork project (because I had to adapt the code with yunohost 11.1) to come back with the old config... but it seems not resolving why users not receive confirmation and can't sign up...

**Pull request merged**
