### PR TITLE
Fix smtp

### LINKED ISSUE #140: E-Mail verification from users without an account doesn't work
Hi there,

I am on the latest version. I have created an event and sent the link to people without a mobilizon account. They want to take part, but they don't get the verification mail.

Do I need to setup mail manually?

Regards,

Stefan

### PR DESCRIPTION
**Pull request by rodinux**
## Problem

- the Swoosh adapters smtp did not work since the fix #140

## Solution

- Come back to use Bamboo smtp adapter

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by rodinux** [comment]
Hello,
I found how debug my instance for make the mail working. Use Bamboo Adapter is the only way, this version of Mobilizon have the module Bamboo_smtp not Swoosh needed only when upgrading to version 2.1.
Please, take care, I finally can use mail on my instance with this fix, it was broken since the last PR...

**Comment by rodinux** [comment]
!testme

**Comment by rodinux** [comment]
!testme

**Comment by rodinux** [comment]
!testme

**Comment by rodinux** [comment]
!testme

**Comment by rodinux** [comment]
@yalh76 I add this PR to fix smpt for receive and sending mails... I haven't care before but I really think the last PR broke this possibility, Swoosh adpater smpt will be avalaible on next release but not with this version...

**Review by yalh76 — APPROVED** [review]

**Pull request merged**
