### PR TITLE
Upgrade to version 3.1.3

### LINKED ISSUE #35: Install fail - missing postgresql-13-postgis-3 dependency
Installation of Mobilizon has failed! 
Here is the end of the logfile.
```
2019-11-13 23:14:40,826: DEBUG - 
2019-11-13 23:14:40,827: DEBUG - 23:14:40.800 [info]  == Running 20180109150000 Mobilizon.Repo.Migrations.Prerequites.up/0 forward
2019-11-13 23:14:40,827: DEBUG - 
2019-11-13 23:14:40,827: DEBUG - 23:14:40.801 [info]  execute "CREATE TYPE datetimetz AS (\n    dt timestamptz,\n    tz varchar\n);\n"
2019-11-13 23:14:40,827: DEBUG - 
2019-11-13 23:14:40,828: DEBUG - 23:14:40.815 [info]  execute "CREATE EXTENSION IF NOT EXISTS postgis"
2019-11-13 23:14:40,928: DEBUG - + ynh_exit_properly
2019-11-13 23:14:40,929: WARNING - ** (Postgrex.Error) ERROR 58P01 (undefined_file) could not open extension control file "/usr/share/postgresql/9.6/extension/postgis.control": No such file or directory
2019-11-13 23:14:40,934: DEBUG - + local exit_code=1
```

### LINKED ISSUE #124: Can't Upgrade to 2.0
### Describe the bug

everything seems to be configured correctly, previous upgrades up to 1.3 went fine but upgrade to 2.0 didn't work. Seems Mobilizon executable hooks into the "wrong port".
Since everything is configured to use port :8097, I don't understand why Mobilizon's "epmd" insists on using port ":4369".

### Context

- Hardware: *VPS bought online 
- YunoHost version: 4.3.5
- I have access to my server: Through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Expected behavior

Mobilizon to run version 2.0

### Logs

https://paste.yunohost.org/raw/elucexanoc

### LINKED ISSUE #130: Installation failed on aarm64 missing GLIBC_2.29
Installation failed on aarm64 

- Hardware: raspberry Pi4 
- YunoHost version: 4.3.6.2 (stable)
- I have access to my server: Through SSH | through the webadmin | direct access via keyboard /
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?:  yes installed via script on raspbian arm64
 - trying to install package version/branch: master
-  error log complains about `GLIBC_2.29' not found

Logs
[https://paste.yunohost.org/raw/merohaqone](https://paste.yunohost.org/raw/merohaqone)

### LINKED ISSUE #135: Can't login after upgrade to 2.1.0~ynh1
### Describe the bug

*can't login after last update*

### Context

- Hardware: *VPS bought online*
- YunoHost version: 4.3.6.3
- I have access to my server: *Through SSH | through the webadmin.*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
I have move some data folders or apps on dedicated partitions
- If upgrading, current package version: *can be found in the admin, or with `yunohost app info $app_id`* 
- Upgrading to 2.1.0~ynh1

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sh
    sudo yunohost app upgrade mobilizon
    ```

   1. *Go to 'page login'*
   2. *Click on 'Se connecter' after put my credentials*
   4. *See error: `Impossible de s'authentifier, votre adresse e-mail ou bien votre mot de passe sont invalides.`*

### Expected behavior

*Login with my credentials which are the admin user*

### Logs

*When an operation fails, YunoHost provides a simple way to share the logs.*
- *In the webadmin, the error message contains a link to the relevant log page. On that page, you will be able to 'Share with Yunopaste'. If you missed it, the logs of previous operations are also available under Tools > Logs.*
- *In command line, the command to share the logs is displayed at the end of the operation and looks like `yunohost log display [log name] --share`. If you missed it, you can find the log ID of a previous operation using `yunohost log list`.*

*After sharing the log, please copypaste directly the link provided by YunoHost (to help readability, no need to copypaste the entire content of the log here, just the link is enough...)*

*If applicable and useful, add screenshots to help explain your problem.*
 some logs in nginx ( domain.domainname.tld-error.log )

```
2022/06/19 19:59:50 [error] 13740#13740: *1193146 connect() failed (111: Connection refused) while connecting to upstream, client: XX.XX.XX.XXX, server: domain.domainname.tld, request: "POST /api HTTP/2.0", upstream: "http://[::1]:8095/api", host: "domain.domainname.tld", referrer: "https://domain.domainname.tld/"
2022/06/19 20:00:01 [error] 13740#13740: *1193146 connect() failed (111: Connection refused) while connecting to upstream, client: XX.XX.XX.XXX, server: domain.domainname.tld, request: "GET /fonts/materialdesignicons-webfont.f5b84261.ttf HTTP/2.0", upstream: "http://[::1]:8095/fonts/materialdesignicons-webfont.f5b84261.ttf", host: "domain.domainname.tld", referrer: "https://domain.domainname.tld/service-worker.js"
2022/06/19 20:00:32 [error] 13740#13740: *1193175 connect() failed (111: Connection refused) while connecting to upstream, client: XXXX:XXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX, server: domain.domainname.tld, request: "GET /.well-known/host-meta HTTP/2.0", upstream: "http://[::1]:8095/.well-known/host-meta", host: "domain.domainname.tld"
2022/06/19 20:01:47 [error] 13740#13740: *1193183 connect() failed (111: Connection refused) while connecting to upstream, client: XXXX:XXXX:X:X::XXX, server: domain.domainname.tld, request: "GET /.well-known/nodeinfo/2.1 HTTP/2.0", upstream: "http://[::1]:8095/.well-known/nodeinfo/2.1", host: "domain.domainname.tld"
2022/06/19 20:02:20 [error] 13740#13740: *1193188 connect() failed (111: Connection refused) while connecting to upstream, client: XXX.XXX.XXX.XX, server: domain.domainname.tld, request: "GET /.well-known/nodeinfo/2.1 HTTP/2.0", upstream: "http://[::1]:8095/.well-known/nodeinfo/2.1", host: "domain.domainname.tld"
2022/06/19 20:04:28 [error] 13740#13740: *1193207 connect() failed (111: Connection refused) while connecting to upstream, client: XX.XXX.XXX.XX, server: domain.domainname.tld, request: "GET /.well-known/nodeinfo/2.1 HTTP/1.1", upstream: "http://[::1]:8095/.well-known/nodeinfo/2.1", host: "domain.domainname.tld"
2022/06/19 20:12:25 [error] 13740#13740: *1193260 connect() failed (111: Connection refused) while connecting to upstream, client: XXXX:XXXX:X:XX::XXXX:XXXX, server: domain.domainname.tld, request: "HEAD /nodeinfo/2.1.json HTTP/1.1", upstream: "http://[::1]:8095/nodeinfo/2.1.json", host: "domain.domainname.tld"
2022/06/19 20:12:38 [error] 13740#13740: *1193291 connect() failed (111: Connection refused) while connecting to upstream, client: XXXX:XXXX:X:XX::XXXX:XXXX, server: domain.domainname.tld, request: "HEAD /nodeinfo/2.0.json HTTP/1.1", upstream: "http://[::1]:8095/nodeinfo/2.0.json", host: "domain.domainname.tld"
2022/06/19 20:12:51 [error] 13740#13740: *1193318 connect() failed (111: Connection refused) while connecting to upstream, client: XXXX:XXXX:X:XX::XXXX:XXXX, server: domain.domainname.tld, request: "GET /api/v1/instance/nodeinfo/2.0 HTTP/1.1", upstream: "http://[::1]:8095/api/v1/instance/nodeinfo/2.0", host: "domain.domainname.tld"
2022/06/19 20:29:24 [error] 13740#13740: *1193440 connect() failed (111: Connection refused) while connecting to upstream, client: XXX.XX.XXX.XXX, server: domain.domainname.tld, request: "GET /api/v1/instance HTTP/1.1", upstream: "http://[::1]:8095/api/v1/instance", host: "domain.domainname.tld"
```

### LINKED ISSUE #158: Break the yunohost 4 -> 11 postgresql migration
postgis postgresql module is not considered in ynh postgresql migration. So going onto YunoHost 11 is not easy. Be sure to have backup of your postgresql DB before to try the migration.

See https://github.com/YunoHost/yunohost/pull/1567

### LINKED ISSUE #166: Mobilizon 3 is out and stable!!!
Hi, please could you update to the new major version? 🙏 
https://github.com/framasoft/mobilizon/blob/main/CHANGELOG.md

Latest is `3.1.1` and it seems very stable and more polished, you can test the french instance here: https://mobilizon.fr/
Would help a lot **activists all over the world without tech skills** if you can upgrade this package!

Thank you @yalh76 @rodinux @alexAubin @yunohost-bot @oufmilo @thom4parisot @ericgaspar

### PR DESCRIPTION
**Pull request by yalh76**
## Problem

- *Fix #35*
- *Fix #124*
- *Fix #130*
- *Fix #135*
- *Fix #158*
- *Close #164*
- *Close #166*

## Solution

- *Upgrade to version 3.1.3*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by rodinux** [comment]
Ok, I have 2 suggestions. I have done a lot of tests also on a local Yunohost. 

1. For the stable branch version 2.0.2, please, it works with my suggestion with the PR https://github.com/YunoHost-Apps/mobilizon_ynh/pull/153 to have mail and sign up available !!
2. For this update, the Swoosh smtp Adapter works, so all good, but we still have the bug with LDAP, the admin user can not connect back after this upgrade, only visitors can do it...

I can try now found logs, I have try on a local server with virtualbox install mobilizon, update with my fix https://github.com/YunoHost-Apps/mobilizon_ynh/pull/153, all was working. Then upgrade with the testing branch 3.0.1.

For example, after upgrading I couldn't sign in with my LDAP admin user, I have these logs if it helps ??

**/var/log/syslog**

```
Dec 16 00:00:00 yunohost mobilizon[25976]: 00:00:00.573 [info] {"args":{},"attempt":1,"duration":390067,"event":"job:stop","id":1,"max_attempts":20,"meta":{},"queue":"background","queue_time":48376,"source":"oban","state":"success","tags":[],"worker":"Mobilizon.Service.Workers.BuildSiteMap"}
Dec 16 00:00:08 yunohost systemd[1]: Starting Rotate log files...
Dec 16 00:00:08 yunohost systemd[1]: Starting Daily man-db regeneration...
Dec 16 00:00:09 yunohost systemd[1]: Reloading LSB: Metronome XMPP Server.
Dec 16 00:00:09 yunohost metronome[26689]: Reloading Metronome XMPP Server: metronome.
Dec 16 00:00:09 yunohost systemd[1]: Reloaded LSB: Metronome XMPP Server.
Dec 16 00:00:09 yunohost systemd[1]: rspamd.service: Sent signal SIGUSR1 to main process 911 (rspamd) on client request.
Dec 16 00:00:09 yunohost systemd[1]: rspamd.service: Sending signal SIGUSR1 to process 1405 (rspamd) on client request.
Dec 16 00:00:09 yunohost systemd[1]: rspamd.service: Sending signal SIGUSR1 to process 1406 (rspamd) on client request.
Dec 16 00:00:09 yunohost systemd[1]: rspamd.service: Sending signal SIGUSR1 to process 1407 (rspamd) on client request.
Dec 16 00:00:09 yunohost systemd[1]: rspamd.service: Sending signal SIGUSR1 to process 1408 (rspamd) on client request.
Dec 16 00:00:09 yunohost systemd[1]: logrotate.service: Succeeded.
Dec 16 00:00:09 yunohost systemd[1]: Finished Rotate log files.
Dec 16 00:00:09 yunohost mobilizon[25976]: 00:00:09.752 request_id=FzEZttNoGfOJmlEAAAcx [info] POST /api
Dec 16 00:00:10 yunohost mobilizon[25976]: 00:00:10.072 request_id=FzEZttNoGfOJmlEAAAcx graphql_operation_name=#NULL [info] Sent 200 in 319ms
Dec 16 00:00:10 yunohost systemd[1]: man-db.service: Succeeded.
Dec 16 00:00:10 yunohost systemd[1]: Finished Daily man-db regeneration.
Dec 16 00:00:15 yunohost mobilizon[25976]: 00:00:15.990 request_id=FzEZuEc56u5rCxQAAAex [info] POST /api
Dec 16 00:00:16 yunohost mobilizon[25976]: 00:00:16.020 request_id=FzEZuEc56u5rCxQAAAex graphql_operation_name=CategoryStatistics [info] Sent 200 in 29ms
Dec 16 00:00:16 yunohost mobilizon[25976]: 00:00:16.047 request_id=FzEZuEqR5HkK3h4AAAfx [info] POST /api
Dec 16 00:00:16 yunohost mobilizon[25976]: 00:00:16.117 request_id=FzEZuEqR5HkK3h4AAAfx graphql_operation_name=SearchEvents [info] Sent 200 in 70ms
Dec 16 00:00:16 yunohost mobilizon[25976]: 00:00:16.140 request_id=FzEZuFAnrMyKR4AAAAhB [info] POST /api
Dec 16 00:00:16 yunohost mobilizon[25976]: 00:00:16.204 request_id=FzEZuFAnrMyKR4AAAAhB graphql_operation_name=FetchEvents [info] Sent 200 in 63ms
Dec 16 00:05:01 yunohost CRON[26815]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Dec 16 00:09:01 yunohost CRON[26834]: (root) CMD (  [ -x /usr/lib/php/sessionclean ] && if [ ! -d /run/systemd/system ]; then /usr/lib/php/sessionclean; fi)
Dec 16 00:09:08 yunohost systemd[1]: Starting Clean php session files...
Dec 16 00:09:09 yunohost systemd[1]: phpsessionclean.service: Succeeded.
Dec 16 00:09:09 yunohost systemd[1]: Finished Clean php session files.
Dec 16 00:12:49 yunohost slapd[786]: slap_global_control: unrecognized control: 1.3.6.1.4.1.4203.666.5.16
Dec 16 00:12:49 yunohost slapd[786]: slap_global_control: unrecognized control: 1.3.6.1.4.1.4203.666.5.16
Dec 16 00:12:49 yunohost slapd[786]: slap_global_control: unrecognized control: 1.3.6.1.4.1.4203.666.5.16
Dec 16 00:12:49 yunohost slapd[786]: slap_global_control: unrecognized control: 1.3.6.1.4.1.4203.666.5.16
Dec 16 00:13:58 yunohost slapd[786]: slap_global_control: unrecognized control: 1.3.6.1.4.1.4203.666.5.16
Dec 16 00:13:58 yunohost slapd[786]: slap_global_control: unrecognized control: 1.3.6.1.4.1.4203.666.5.16
Dec 16 00:14:13 yunohost nslcd[1003]: [a1821b] <passwd="*"> request denied by validnames option
Dec 16 00:15:01 yunohost CRON[26990]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Dec 16 00:17:01 yunohost CRON[27007]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Dec 16 00:17:05 yunohost nslcd[1003]: [e67713] <passwd="*"> request denied by validnames option
Dec 16 00:17:36 yunohost nslcd[1003]: [5c55b5] <passwd="*"> request denied by validnames option
Dec 16 00:17:42 yunohost postfix/qmgr[2706]: 002147FED2: from=<mobilizon@mobilizon.yunohost.packaging>, size=13396, nrcpt=1 (queue active)
Dec 16 00:17:42 yunohost postfix/smtp[27029]: 002147FED2: host smtp-in.sfr.fr[93.17.128.165] refused to talk to me: 554 5.7.1 Service unavailable; Client host [37.167.254.28] blocked using pbl.spamhaus.sfr; https://www.spamhaus.org/query/ip/37.167.254.28
Dec 16 00:17:42 yunohost postfix/smtp[27029]: 002147FED2: to=<rodolphe.robles@sfr.fr>, relay=smtp-in.sfr.fr[93.17.128.123]:25, delay=2363, delays=2362/0.1/0.33/0, dsn=4.7.1, status=deferred (host smtp-in.sfr.fr[93.17.128.123] refused to talk to me: 554 5.7.1 Service unavailable; Client host [37.167.254.28] blocked using pbl.spamhaus.sfr; https://www.spamhaus.org/query/ip/37.167.254.28)
Dec 16 00:17:58 yunohost nslcd[1003]: [a62aca] <passwd="*"> request denied by validnames option
Dec 16 00:21:25 yunohost nslcd[1003]: [fce74e] <passwd="*"> request denied by validnames option
Dec 16 00:21:48 yunohost nslcd[1003]: [3dd3e8] <passwd="*"> request denied by validnames option
Dec 16 00:22:19 yunohost nslcd[1003]: [c91298] <passwd="*"> request denied by validnames option
Dec 16 00:25:01 yunohost CRON[27105]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
```
**/var/log/nginx/mobilizon.yunohost.packaging-error.log**

`Dec 16 00:17:58 yunohost nslcd[1003]: [a62aca] <passwd="*"> request denied by validnames option`

**journalctl -u mobilizon -f**
```
Dec 16 00:17:58 yunohost nslcd[1003]: [a62aca] <passwd="*"> request denied by validnames option
Dec 16 00:21:25 yunohost nslcd[1003]: [fce74e] <passwd="*"> request denied by validnames option
Dec 16 00:21:48 yunohost nslcd[1003]: [3dd3e8] <passwd="*"> request denied by validnames option
Dec 16 00:22:19 yunohost nslcd[1003]: [c91298] <passwd="*"> request denied by validnames option
Dec 16 00:25:01 yunohost CRON[27105]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
root@yunohost:/var/log# journalctl -u mobilizon -f
-- Journal begins at Thu 2022-11-10 22:49:33 CET. --
déc. 16 00:00:00 yunohost.packaging mobilizon[25976]: 00:00:00.212 [info] {"args":{},"attempt":1,"duration":27053,"event":"job:stop","id":2,"max_attempts":20,"meta":{},"queue":"background","queue_time":48376,"source":"oban","state":"success","tags":[],"worker":"Mobilizon.Service.Workers.CleanOrphanMediaWorker"}
déc. 16 00:00:00 yunohost.packaging mobilizon[25976]: 00:00:00.573 [info] {"args":{},"attempt":1,"duration":390067,"event":"job:stop","id":1,"max_attempts":20,"meta":{},"queue":"background","queue_time":48376,"source":"oban","state":"success","tags":[],"worker":"Mobilizon.Service.Workers.BuildSiteMap"}
déc. 16 00:00:09 yunohost.packaging mobilizon[25976]: 00:00:09.752 request_id=FzEZttNoGfOJmlEAAAcx [info] POST /api
déc. 16 00:00:10 yunohost.packaging mobilizon[25976]: 00:00:10.072 request_id=FzEZttNoGfOJmlEAAAcx graphql_operation_name=#NULL [info] Sent 200 in 319ms
déc. 16 00:00:15 yunohost.packaging mobilizon[25976]: 00:00:15.990 request_id=FzEZuEc56u5rCxQAAAex [info] POST /api
déc. 16 00:00:16 yunohost.packaging mobilizon[25976]: 00:00:16.020 request_id=FzEZuEc56u5rCxQAAAex graphql_operation_name=CategoryStatistics [info] Sent 200 in 29ms
déc. 16 00:00:16 yunohost.packaging mobilizon[25976]: 00:00:16.047 request_id=FzEZuEqR5HkK3h4AAAfx [info] POST /api
déc. 16 00:00:16 yunohost.packaging mobilizon[25976]: 00:00:16.117 request_id=FzEZuEqR5HkK3h4AAAfx graphql_operation_name=SearchEvents [info] Sent 200 in 70ms
déc. 16 00:00:16 yunohost.packaging mobilizon[25976]: 00:00:16.140 request_id=FzEZuFAnrMyKR4AAAAhB [info] POST /api
déc. 16 00:00:16 yunohost.packaging mobilizon[25976]: 00:00:16.204 request_id=FzEZuFAnrMyKR4AAAAhB graphql_operation_name=FetchEvents [info] Sent 200 in 63ms
```

**Comment by Gredin67** [comment]
```
janv. 14 11:21:18 mobilizon[29961]: 11:21:18.483 request_id=FzoltseMk8-XP50AABwh [info] POST /api
janv. 14 11:21:18 mobilizon[29961]: 11:21:18.716 request_id=FzoltseMk8-XP50AABwh graphql_operation_name=FetchEvent [info] Sent 200 in 232ms
janv. 14 11:21:19 mobilizon[29961]: 11:21:19.633 request_id=FzoltwwbpqTx_KsAAB5h [info] POST /api
janv. 14 11:21:19 mobilizon[29961]: 11:21:19.658 request_id=FzoltwwbpqTx_KsAAB5h graphql_operation_name=CommentThreadsWithReplies [info] Sent 200 in 24ms
janv. 14 11:21:47 mobilizon[29961]: 11:21:47.147 request_id=FzolvXQF8j8cpRIAAB6h [info] POST /api
janv. 14 11:21:47 mobilizon[29961]: 11:21:47.151 request_id=FzolvXQF8j8cpRIAAB6h graphql_operation_name=Login [info] Sent 200 in 4ms
janv. 14 11:22:49 mobilizon[29961]: 11:22:49.866 request_id=FzolzA5f-dpDS1IAAB8B [info] POST /api
janv. 14 11:22:49 mobilizon[29961]: 11:22:49.871 request_id=FzolzA5f-dpDS1IAAB8B graphql_operation_name=Login [info] Sent 200 in 4ms
```

**Comment by yalh76** [comment]
smtp stuff has been merged in master. so putting this PR in draft, waiting for mobilizon 3.0.4 with a working ldap

**Comment by rodinux** [comment]
> smtp stuff has been merged in master. so putting this PR in draft, waiting for mobilizon 3.0.4 with a working ldap

It's will be soon here to test it ! https://packages.joinmobilizon.org/3.0.4/

**Comment by Gredin67** [comment]
@yalh76 @rodinux did anybody else experience the issue after this upgrade ?

**Comment by rodinux** [comment]
Hello @yalh76 @Gredin67 , I can explain after testing, we need change the parameters for Webmail:

```
  #adapter: Bamboo.SMTPAdapter,
  #server: "127.0.0.1",
  adapter: Swoosh.Adapters.SMTP,
  relay: "127.0.0.1",
```

The adapter.Bamboo..SMTPAdapter don't works with this release

```
mai 08 14:18:19 rodinux.fr mobilizon[207802]: ** (exit) an exception was raised:
mai 08 14:18:19 rodinux.fr mobilizon[207802]:     ** (UndefinedFunctionError) function Bamboo.SMTPAdapter.validate_config/1 is undefined (module Bamboo.SMTPAdapter is not available)
```

I have mails working with these changes but users from outside can not sign in... If I try resent a new password (or I forgot my password), the link to reset the password is not good... 

Capture d’écran du 2023-05-08 14-58-54

**Comment by rodinux** [comment]
Here some logs...

```
mai 08 14:48:16 rodinux.fr mobilizon[213259]: 14:48:16.584 request_id=F10r5JyEBuKir5oAAAhC [info] POST /api
mai 08 14:48:16 rodinux.fr mobilizon[213259]: 14:48:16.587 request_id=F10r5JyEBuKir5oAAAhC graphql_operation_name=Login [info] Sent 200 in 2ms
mai 08 14:48:32 rodinux.fr mobilizon[213259]: 14:48:32.316 request_id=F10r6EY27UX8SMkAAAii [info] GET /login
mai 08 14:48:32 rodinux.fr mobilizon[213259]: 14:48:32.320 request_id=F10r6EY27UX8SMkAAAii [info] Sent 200 in 3ms
mai 08 14:48:32 rodinux.fr mobilizon[213259]: 14:48:32.995 request_id=F10r6G6wq_lKVioAAAjC [info] POST /api
mai 08 14:48:33 rodinux.fr mobilizon[213259]: 14:48:33.005 request_id=F10r6G6wq_lKVioAAAjC graphql_operation_name=FullConfig [info] Sent 200 in 9ms
mai 08 14:49:07 rodinux.fr mobilizon[213259]: 14:49:07.858 request_id=F10r8IytMjyWitkAAAgB [info] POST /api
mai 08 14:49:07 rodinux.fr mobilizon[213259]: 14:49:07.861 request_id=F10r8IytMjyWitkAAAgB graphql_operation_name=Login [info] Sent 200 in 3ms
mai 08 14:49:40 rodinux.fr mobilizon[213259]: 14:49:40.007 request_id=F10r-AjpHDjJgL4AAAhh [info] POST /api
mai 08 14:49:40 rodinux.fr mobilizon[213259]: 14:49:40.088 request_id=F10r-AjpHDjJgL4AAAhh [warning] Description: 'Authenticity is not established by certificate path validation'
mai 08 14:49:40 rodinux.fr mobilizon[213259]:      Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'
mai 08 14:49:40 rodinux.fr mobilizon[213259]: 14:49:40.365 request_id=F10r-AjpHDjJgL4AAAhh graphql_operation_name=SendResetPassword [info] Sent 200 in 357ms
mai 08 14:49:52 rodinux.fr mobilizon[213259]: 14:49:52.237 request_id=F10r-uHg2QOtbvEAAAkB [info] GET /password-reset/8bTEujyKTReTYUk0e4gKOVuw2TrsoRhZVIOmCHW7
mai 08 14:49:52 rodinux.fr mobilizon[213259]: 14:49:52.240 request_id=F10r-uHg2QOtbvEAAAkB [info] Sent 200 in 2ms
mai 08 14:49:53 rodinux.fr mobilizon[213259]: 14:49:53.009 request_id=F10r-w_cBGyXkVkAAAkh [info] POST /api
mai 08 14:49:53 rodinux.fr mobilizon[213259]: 14:49:53.022 request_id=F10r-w_cBGyXkVkAAAkh graphql_operation_name=FullConfig [info] Sent 200 in 12ms
mai 08 14:50:30 rodinux.fr mobilizon[213259]: 14:50:30.838 request_id=F10sA96r9fu1RUgAAAmh [info] POST /api
mai 08 14:50:31 rodinux.fr mobilizon[213259]: 14:50:31.222 request_id=F10sA96r9fu1RUgAAAmh [warning] Failed to send Sentry event. Cannot send Sentry event because of invalid DSN
mai 08 14:50:31 rodinux.fr mobilizon[213259]: 14:50:31.223 request_id=F10sA96r9fu1RUgAAAmh [info] Sent 500 in 384ms
mai 08 14:50:31 rodinux.fr mobilizon[213259]: 14:50:31.224 [error] #PID<0.4758.0> running Mobilizon.Web.Endpoint (connection #PID<0.4757.0>, stream id 1) terminated
mai 08 14:50:31 rodinux.fr mobilizon[213259]: Server: mobilizon.rodinux.fr:80 (http)
mai 08 14:50:31 rodinux.fr mobilizon[213259]: Request: POST /api
mai 08 14:50:31 rodinux.fr mobilizon[213259]: ** (exit) an exception was raised:
mai 08 14:50:31 rodinux.fr mobilizon[213259]:     ** (MatchError) no match of right hand side value: {:error, {:ok, {:eldap_search_result, [], [], :asn1_NOVALUE}}}
mai 08 14:50:31 rodinux.fr mobilizon[213259]:         (mobilizon 3.0.4) lib/graphql/resolvers/user.ex:328: Mobilizon.GraphQL.Resolvers.User.reset_password/3
mai 08 14:50:31 rodinux.fr mobilizon[213259]:         (absinthe 1.7.0) lib/absinthe/resolution.ex:209: Absinthe.Resolution.call/2
mai 08 14:50:31 rodinux.fr mobilizon[213259]:         (absinthe 1.7.0) lib/absinthe/phase/document/execution/resolution.ex:230: Absinthe.Phase.Document.Execution.Resolution.reduce_resolution/1
mai 08 14:50:31 rodinux.fr mobilizon[213259]:         (absinthe 1.7.0) lib/absinthe/phase/document/execution/resolution.ex:185: Absinthe.Phase.Document.Execution.Resolution.do_resolve_field/3
mai 08 14:50:31 rodinux.fr mobilizon[213259]:         (absinthe 1.7.0) lib/absinthe/phase/document/execution/resolution.ex:170: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6
mai 08 14:50:31 rodinux.fr mobilizon[213259]:         (absinthe 1.7.0) lib/absinthe/phase/document/execution/resolution.ex:88: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
mai 08 14:50:31 rodinux.fr mobilizon[213259]:         (absinthe 1.7.0) lib/absinthe/phase/document/execution/resolution.ex:67: Absinthe.Phase.Document.Execution.Resolution.perform_resolution/3
mai 08 14:50:31 rodinux.fr mobilizon[213259]:         (absinthe 1.7.0) lib/absinthe/phase/document/execution/resolution.ex:24: Absinthe.Phase.Document.Execution.Resolution.resolve_current/3
mai 08 14:50:31 rodinux.fr mobilizon[213259]: 14:50:31.896 request_id=F10sBB29voYkLd8AAAoh [info] POST /api
mai 08 14:50:31 rodinux.fr mobilizon[213259]: 14:50:31.899 request_id=F10sBB29voYkLd8AAAoh graphql_operation_name=ResetPassword [info] Sent 200 in 2ms
```

It is very strange, because I can create a new account with a mail from outside, and get a first connexion, but If I want to sign in again after a sign out, it did not works...

**Comment by rodinux** [comment]
Par contre comme expliqué ici: https://framagit.org/framasoft/mobilizon/-/issues/1130#note_1947471

Si j'inverse l'ordre des authentifications, le LDAP est désactivé mais les utilisateurs externes peuvent se connecter:

```
config :mobilizon, Mobilizon.Service.Auth.LDAPAuthenticator, Mobilizon.Service.Auth.Authenticator
```
au lieu de 

```
config :mobilizon, Mobilizon.Service.Auth.Authenticator, Mobilizon.Service.Auth.LDAPAuthenticator, 
```

cela m'oblige à créer ou modifier un utilisateur externe en admin

```
/var/www/mobilizon/live# sudo -u mobilizon ./bin/mobilizon_ctl users.modify "user@domaine.tld" --admin
```

Par contre l'user LDAP ne peux plus se connecter, Mobilizon lit sa bdd et non le LDAP...

**Comment by rodinux** [comment]
Par contre certains profils sont inversés !! très bizarre

**Comment by ericgaspar** [comment]
!testme

**Review by alexAubin — APPROVED** [review]
LGTM though I don't know if the major migration 2->3 is properly tested :sweat_smile:

**Comment by ericgaspar** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Pull request merged**
