### PR TITLE
Update to 1.1.4

### PR DESCRIPTION
**Pull request by yalh76**
## Solution

- *Update to 1.1.4*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by oufmilo** [comment]
i don't understand why multi instance is failed

**Comment by yalh76** [comment]
#Own CI results for Revision: 835236b87e8b061a7d3471151502eb664171dcf5 

image

**Comment by yalh76** [comment]
> 
> 
> i don't understand why multi instance is failed

Usually it's because of a lack of space ^^

**Pull request merged**
