### PR TITLE
Fix mail

### PR DESCRIPTION
**Pull request by yalh76**
## Problem
- *Not sending emails*

## Solution
- *Fix it*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/mobilizon_ynh%20PR50%20(yalh76)/)

### CODE REVIEW

**Comment by oufmilo** [comment]
Okay, so I'm not the only one who didn't get the confirmation email.

**Comment by alexAubin** [comment]
(Apparently this is not relevant anymore because the way the app works changed and this config file disappeared?)

**Comment by yalh76** [comment]
yes no more usefull

**Comment by alexAubin** [comment]
(Sorry for randomly reopening this : it sounds like it in fact still relevant because we do want mail notifications ... it's just that it now has to go into prod.secret.exs instead of prod.exs ...

relevant documentation : https://docs.joinmobilizon.org/administration/configure/email/ )

**Comment by alexAubin** [comment]
Re-closing because it's now integrated in testing, sorry for the noise !

**Pull request closed without merging**
